/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chintu
 */
import java.sql.*;
import javax.swing.*;

public class allot extends javax.swing.JFrame {
 Connection conn=null;
    ResultSet a;
    int i;
    String d;
   
    /**
     * Creates new form allot
     */
    public allot() {
        initComponents();
    }
     public allot(ResultSet rs,int k) {
         a=rs;
         i=k;
         d=Integer.toString(i);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText(d);

        enterc.setBackground(new java.awt.Color(0, 0, 51));
        enterc.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("FINISH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(0, 0, 51));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"IIT KGP", 1, 2, 3, 4, 5, 6, 7, 8, 9, 10},
                {"IIT BOMBAY", 11,12, 13, 14, 15, 16, 17, 18, 19, 20},
                {"IIT D", 21, 22, 23, 24, 25, 26, 27, 28, 29, 30},
                {"IIT M", 31, 32, 33, 34, 35,36 , 37, 38, 39, 40},
                {"IIT H", 41, 42, 43, 44, 45, 46, 47,48, 49, 50},
                {"IIT R", 51, 52, 53, 54, 55, 56, 57, 58, 59, 60},
                {"IIT K", 61, 62, 63, 64, 65, 66, 67, 68, 69, 70},
                {"IIT G", 71, 72, 73, 74, 75, 76, 77, 78, 79, 80},
                {"IIT I", 81, 82, 83,84, 85, 86, 87, 88, 89, 90},
                {"IIT BN", 91,92, 93,94,95,96,97,98,99,100},
                {"IIT GN", 101,102,103,104,105,106,107,108,109,110},
                {"IIT RP", 111,112,113,114,115,116,117,118,118,119,120}
            },
            new String [] {
                "College Name", "csebt", "csed", "ecebt", "eced", "mechbt", "mechd", "elecbt", "elecd", "civilbt", "civild"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(jLabel1)
                        .addGap(89, 89, 89)
                        .addComponent(enterc))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(139, 139, 139)
                        .addComponent(jButton2)))
                .addGap(264, 264, 264))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          int k=Integer.parseInt(enterc.getText());
         if(i==1){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p1='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
             if(i==2){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p2='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
                 if(i==3){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p3='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
             if(i==4){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p4='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         } 
                 if(i==5){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p5='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
                     if(i==6){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p6='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
                         if(i==7){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p7='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==8){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p8='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==9){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p9='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==10){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p10='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==11){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p11='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==12){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p12='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==13){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p13='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==104){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p14='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==15){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p15='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==16){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p16='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
             if(i==17){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p17='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==18){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p18='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==19){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p19='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==20){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p20='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
             if(i==21){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p21='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
                 if(i==22){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p22='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==23){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p23='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
             if(i==24){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p24='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==25){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p25='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
             if(i==26){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p26='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==27){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p27='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         
         }
             if(i==28){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p28='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==29){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p29='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==30){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p30='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==31){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p31='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
            if(i==32){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p32='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
   if(i==33){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p33='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
   if(i==34){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p34='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
   if(i==35){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p35='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
   if(i==36){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p36='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }    if(i==37){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p37='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
   if(i==38){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p38='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
   if(i==39){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p39='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
   if(i==40){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p40='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
 if(i==41){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p41='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
 if(i==42){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p42='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
 if(i==43){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p43='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
 if(i==44){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p44='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
 if(i==45){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p45='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
 if(i==46){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p46='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
 if(i==47){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p47='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
 if(i==48){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p48='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
 if(i==49){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p49='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
 if(i==50){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p50='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
if(i==51){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p51='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
if(i==52){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p52='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
if(i==53){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p53='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
if(i==54){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p54='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
if(i==55){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p55='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
if(i==56){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p56='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
if(i==57){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p57='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
if(i==58){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p58='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
if(i==59){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p59='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
if(i==60){
            try{
                 Class.forName("com.mysql.jdbc.Driver");
      conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
                String sql1;
             int p=a.getInt("Rank");
             PreparedStatement pst1=null;
             
              sql1="update student set p60='"+k+"' where Rank='"+p+"' ";
              pst1=conn.prepareStatement(sql1);
              pst1.executeUpdate();
            
              allot q=new allot(a,i+1);
              q.setVisible(true);
              this.dispose();
         } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }  
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        home v=new home(a);
        v.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(allot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(allot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(allot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(allot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new allot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField enterc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
