/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chintu
 */
import java.sql.*;
import javax.swing.*;
public class home extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }
    ResultSet a=null;
    String n,b,c,m,e;
     public home(ResultSet rs) {
         a=rs;
         try{
         n=a.getString("FirstName");
         b=a.getString("LastName");
         c=Integer.toString(a.getInt("final"));
         m=Integer.toString(a.getInt("Rank"));
         e=a.getString("Emailid");
         }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
         }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        allot = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        allot.setBackground(new java.awt.Color(255, 255, 255));
        allot.setForeground(new java.awt.Color(0, 0, 51));
        allot.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        allot.setFocusable(false);
        allot.setFont(new java.awt.Font("AR CENA", 1, 36)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel15.setFont(new java.awt.Font("AR CENA", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 51));
        jLabel15.setText("WELCOME");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 130, 240, 40);

        jLabel16.setFont(new java.awt.Font("AR CENA", 0, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 51));
        jLabel16.setText(n);
        jPanel1.add(jLabel16);
        jLabel16.setBounds(220, 260, 400, 40);

        allot.addTab("Home", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("I I T Kharagpur ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(50, 240, 150, 25);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("I I T Hyderabad");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(60, 350, 150, 25);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("I I T Bombay");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(46, 119, 150, 25);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("I I T Guwahati");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(280, 350, 133, 25);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("I I T Ropar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(270, 470, 130, 25);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("I I T Madras");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(270, 240, 130, 25);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("I I T Delhi");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(260, 120, 130, 25);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("I I T Kanpur");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);
        jButton10.setBounds(470, 120, 160, 25);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("I I T Indore");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11);
        jButton11.setBounds(70, 470, 115, 25);

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setText("I I T Gandhi Nagar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14);
        jButton14.setBounds(470, 470, 161, 25);

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton15.setText("I I T Rourkee");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15);
        jButton15.setBounds(480, 240, 160, 20);

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton16.setText("I I T Bhubaneshwar ");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16);
        jButton16.setBounds(480, 350, 175, 25);

        allot.addTab("Colleges", jPanel2);

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));

        jLabel18.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("First Round Of Counseling will be held on ______");

        jLabel19.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("First Round Of Counseling will be held on ______");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(402, Short.MAX_VALUE))
        );

        allot.addTab("Announcements", jPanel5);

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setLayout(null);

        jButton17.setBackground(new java.awt.Color(255, 255, 255));
        jButton17.setFont(new java.awt.Font("AR CENA", 1, 18)); // NOI18N
        jButton17.setText("E C E B.TECH");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton17);
        jButton17.setBounds(110, 210, 260, 31);

        jButton18.setFont(new java.awt.Font("AR CENA", 1, 18)); // NOI18N
        jButton18.setText("C S E B.TECH");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton18);
        jButton18.setBounds(110, 90, 260, 30);

        jButton19.setFont(new java.awt.Font("AR CENA", 1, 18)); // NOI18N
        jButton19.setText("CIVIL ENGG B.TECH");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton19);
        jButton19.setBounds(120, 540, 260, 31);

        jButton20.setFont(new java.awt.Font("AR CENA", 1, 18)); // NOI18N
        jButton20.setText("MECH. ENGG B.TECH");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton20);
        jButton20.setBounds(110, 310, 260, 30);

        jButton21.setFont(new java.awt.Font("AR CENA", 1, 18)); // NOI18N
        jButton21.setText("ELECTRICAL ENGG B.TECH");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton21);
        jButton21.setBounds(120, 420, 260, 31);

        jButton22.setBackground(new java.awt.Color(255, 255, 255));
        jButton22.setFont(new java.awt.Font("AR CENA", 1, 18)); // NOI18N
        jButton22.setText("E C E DUAL");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton22);
        jButton22.setBounds(460, 210, 220, 31);

        jButton23.setFont(new java.awt.Font("AR CENA", 1, 18)); // NOI18N
        jButton23.setText("C S E DUAL");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton23);
        jButton23.setBounds(450, 90, 220, 31);

        jButton24.setFont(new java.awt.Font("AR CENA", 1, 18)); // NOI18N
        jButton24.setText("CIVIL ENGG DUAL");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton24);
        jButton24.setBounds(460, 540, 220, 31);

        jButton25.setFont(new java.awt.Font("AR CENA", 1, 18)); // NOI18N
        jButton25.setText("MECH. ENGG DUAL");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton25);
        jButton25.setBounds(460, 310, 230, 31);

        jButton26.setFont(new java.awt.Font("AR CENA", 1, 18)); // NOI18N
        jButton26.setText("ELECTRICAL ENGG DUAL");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton26);
        jButton26.setBounds(460, 410, 230, 30);

        allot.addTab("Courses", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));
        jPanel4.setLayout(null);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8);
        jPanel8.setBounds(1145, 95, 100, 100);

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setText("jLabel7");
        jPanel4.add(jLabel43);
        jLabel43.setBounds(1201, 335, 44, 15);

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel57.setText("jLabel7");
        jPanel4.add(jLabel57);
        jLabel57.setBounds(1201, 474, 44, 15);

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel58.setText("jLabel7");
        jPanel4.add(jLabel58);
        jLabel58.setBounds(1201, 441, 44, 15);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel60.setText("jLabel7");
        jPanel4.add(jLabel60);
        jLabel60.setBounds(1201, 507, 44, 15);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel61.setText("jLabel7");
        jPanel4.add(jLabel61);
        jLabel61.setBounds(1201, 562, 44, 15);

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel62.setText("jLabel7");
        jPanel4.add(jLabel62);
        jLabel62.setBounds(1201, 533, 44, 15);

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel63.setText("jLabel7");
        jPanel4.add(jLabel63);
        jLabel63.setBounds(1201, 595, 44, 15);

        jButton5.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jButton5.setText("ALLOT NOW");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(100, 20, 145, 39);

        jButton2.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jButton2.setText("FREEZE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(90, 220, 145, 39);

        jButton12.setFont(new java.awt.Font("AR CENA", 0, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 0, 51));
        jButton12.setText("REJECT");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);
        jButton12.setBounds(360, 350, 97, 39);

        jButton13.setFont(new java.awt.Font("AR CENA", 0, 24)); // NOI18N
        jButton13.setText("FLOAT");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13);
        jButton13.setBounds(510, 220, 124, 39);

        jLabel17.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Choose any one and only one");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(210, 120, 280, 30);

        allot.addTab("Allot Priority", jPanel4);

        jPanel6.setBackground(new java.awt.Color(0, 0, 51));
        jPanel6.setLayout(null);

        jLabel1.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name:");
        jPanel6.add(jLabel1);
        jLabel1.setBounds(100, 40, 130, 30);

        jLabel2.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name:");
        jPanel6.add(jLabel2);
        jLabel2.setBounds(100, 110, 140, 30);

        jLabel3.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ALLOTTED COURSE");
        jPanel6.add(jLabel3);
        jLabel3.setBounds(60, 180, 210, 30);

        jLabel4.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rank:");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(110, 260, 100, 30);

        jLabel5.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-mail Id:");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(110, 330, 120, 30);

        jLabel10.setFont(new java.awt.Font("AR CENA", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(n);
        jPanel6.add(jLabel10);
        jLabel10.setBounds(310, 40, 220, 20);

        jLabel11.setFont(new java.awt.Font("AR CENA", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(b);
        jPanel6.add(jLabel11);
        jLabel11.setBounds(310, 110, 240, 20);

        jLabel12.setFont(new java.awt.Font("AR CENA", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(c);
        jPanel6.add(jLabel12);
        jLabel12.setBounds(300, 180, 140, 20);

        jLabel13.setFont(new java.awt.Font("AR CENA", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(m);
        jPanel6.add(jLabel13);
        jLabel13.setBounds(300, 250, 140, 20);

        jLabel14.setFont(new java.awt.Font("AR CENA", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(e);
        jPanel6.add(jLabel14);
        jLabel14.setBounds(300, 330, 290, 30);

        jButton27.setBackground(new java.awt.Color(0, 0, 51));
        jButton27.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setText("LOGOUT");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton27);
        jButton27.setBounds(220, 430, 150, 39);

        allot.addTab("Profile", jPanel6);

        jTable1.setBackground(new java.awt.Color(0, 0, 51));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"IIT KGP", 1, 2, 3, 4, 5, 6, 7, 8, 9, 10},
                {"IIT BOMBAY", 11,12, 13, 14, 15, 16, 17, 18, 19, 20},
                {"IIT D", 21, 22, 23, 24, 25, 26, 27, 28, 29, 30},
                {"IIT M", 31, 32, 33, 34, 35,36 , 37, 38, 39, 40},
                {"IIT H", 41, 42, 43, 44, 45, 46, 47,48, 49, 50},
                {"IIT R", 51, 52, 53, 54, 55, 56, 57, 58, 59, 60},
                {"IIT K", 61, 62, 63, 64, 65, 66, 67, 68, 69, 70},
                {"IIT G", 71, 72, 73, 74, 75, 76, 77, 78, 79, 80},
                {"IIT I", 81, 82, 83,84, 85, 86, 87, 88, 89, 90},
                {"IIT BN", 91,92, 93,94,95,96,97,98,99,100},
                {"IIT GN", 101,102,103,104,105,106,107,108,109,110},
                {"IIT RP", 111,112,113,114,115,116,117,118,118,119,120}
            },
            new String [] {
                "College Name", "csebt", "csed", "ecebt", "eced", "mechbt", "mechd", "elecbt", "elecd", "civilbt", "civild"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(44, 44, 44)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(220, 220, 220)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(220, Short.MAX_VALUE)))
        );

        allot.addTab("Course codes", jPanel9);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setForeground(new java.awt.Color(0, 0, 51));

        jLabel7.setFont(new java.awt.Font("AR CENA", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("CHOOSE");

        jLabel8.setFont(new java.awt.Font("AR CENA", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("HEART...");

        jLabel9.setFont(new java.awt.Font("AR CENA", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("BY");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(152, 152, 152))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addComponent(jLabel9)
                    .addContainerGap(229, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(86, 86, 86))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(379, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(217, 217, 217)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allot, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(allot, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        courseinfo c=new courseinfo(8,a);
        c.setVisible(true);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        courseinfo c=new courseinfo(6,a);
        c.setVisible(true);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        courseinfo c=new courseinfo(10,a);
        c.setVisible(true);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        courseinfo c=new courseinfo(2,a);
        c.setVisible(true);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        courseinfo c=new courseinfo(4,a);
        c.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        courseinfo c=new courseinfo(7,a);
        c.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        courseinfo c=new courseinfo(5,a);
        c.setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        courseinfo c=new courseinfo(9,a);
        c.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        courseinfo c=new courseinfo(1,a);
        c.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        courseinfo c=new courseinfo(3,a);
        c.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");

            String sql;
            sql="SELECT * FROM college "+"WHERE id=9";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            rs.next();
            collegeinfo ci=new collegeinfo(rs,a);
            ci.setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");

            String sql;
            sql="SELECT * FROM college "+"WHERE id=5";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            rs.next();
            collegeinfo ci=new collegeinfo(rs,a);
            ci.setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");

            String sql;
            sql="SELECT * FROM college "+"WHERE id=10";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            rs.next();
            collegeinfo ci=new collegeinfo(rs,a);
            ci.setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");

            String sql;
            sql="SELECT * FROM college "+"WHERE id=8";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            rs.next();
            collegeinfo ci=new collegeinfo(rs,a);
            ci.setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");

            String sql;
            sql="SELECT * FROM college "+"WHERE id=6";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            rs.next();
            collegeinfo ci=new collegeinfo(rs,a);
            ci.setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");

            String sql;
            sql="SELECT * FROM college "+"WHERE id=2";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            rs.next();
            collegeinfo ci=new collegeinfo(rs,a);
            ci.setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");

            String sql;
            sql="SELECT * FROM college "+"WHERE id=3";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            rs.next();
            collegeinfo ci=new collegeinfo(rs,a);
            ci.setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");

            String sql;
            sql="SELECT * FROM college "+"WHERE id=11";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            rs.next();
            collegeinfo ci=new collegeinfo(rs,a);
            ci.setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");

            String sql;
            sql="SELECT * FROM college "+"WHERE id=7";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            rs.next();
            collegeinfo ci=new collegeinfo(rs,a);
            ci.setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");

            String sql;
            sql="SELECT * FROM college "+"WHERE id=1";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            rs.next();
            collegeinfo ci=new collegeinfo(rs,a);
            ci.setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");

            String sql;
            sql="SELECT * FROM college "+"WHERE id=4";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            rs.next();
            collegeinfo ci=new collegeinfo(rs,a);
            ci.setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");

            String sql;
            sql="SELECT * FROM college "+"WHERE id=0";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            rs.next();
            collegeinfo ci=new collegeinfo(rs,a);
            ci.setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        allot f=new allot(a,1);
        f.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try{
              Class.forName("com.mysql.jdbc.Driver");
           conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
        int r=a.getInt("Rank");
     int i=0;
     String sql4="update student set status='"+i+"' where Rank='"+r+"'";
     PreparedStatement pst4;
     pst4=conn.prepareStatement(sql4);
     pst4.executeUpdate();
     jButton2.setVisible(false);
     jButton12.setVisible(false);
      jButton13.setVisible(false);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
      try{
              Class.forName("com.mysql.jdbc.Driver");
           conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
        int r=a.getInt("Rank");
     int i=2;
     String sql4="update student set status='"+i+"' where Rank='"+r+"'";
     PreparedStatement pst4;
     pst4=conn.prepareStatement(sql4);
     pst4.executeUpdate();
     int f=a.getInt("final");
           int d=f-1;
               
               int k=d/10;
               int p=d%10;
                String sql;
                 Class.forName("com.mysql.jdbc.Driver");
           conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
           sql="SELECT * FROM college "+"WHERE id='"+k+"'";
           PreparedStatement pst2 =conn.prepareStatement(sql);
           ResultSet s;
           s=pst2.executeQuery();
           s.next();
      int v=s.getInt(p+7);
          
          
           
          
           
            if(p==0){
                v++;
              String sql3;
            sql3="update college set c1='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            
            }
            if(p==1){
                v++;
              String sql3;
            sql3="update college set c2='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            
            }
            if(p==2){
                v++;
              String sql3;
            sql3="update college set c3='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
           
            }
            if(p==3){
                v++;
              String sql3;
            sql3="update college set c4='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            
            }
            if(p==4){
                v++;
              String sql3;
            sql3="update college set c5='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            
            }
            if(p==5){
                v++;
              String sql3;
            sql3="update college set c6='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
           
            }
            if(p==6){
                v++;
              String sql3;
            sql3="update college set c7='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            
            }
            if(p==7){
                v++;
              String sql3;
            sql3="update college set c8='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            
            }
            if(p==8){
                v++;
              String sql3;
            sql3="update college set c9='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            
            }
            if(p==9){
                v++;
              String sql3;
            sql3="update college set c10='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
          
            }
            jButton2.setVisible(false);
     jButton12.setVisible(false);
      jButton13.setVisible(false);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try{
              Class.forName("com.mysql.jdbc.Driver");
           conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
        int r=a.getInt("Rank");
     int i=1;
     String sql4="update student set status='"+i+"' where Rank='"+r+"'";
     PreparedStatement pst4;
     pst4=conn.prepareStatement(sql4);
     pst4.executeUpdate();
     int f=a.getInt("final");
           int d=f-1;
               
               int k=d/10;
               int p=d%10;
                String sql;
                 Class.forName("com.mysql.jdbc.Driver");
           conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
           sql="SELECT * FROM college "+"WHERE id='"+k+"'";
           PreparedStatement pst2 =conn.prepareStatement(sql);
           ResultSet s;
           s=pst2.executeQuery();
           s.next();
      int v=s.getInt(p+7);
          
          
           
          
           
            if(p==0){
                v++;
              String sql3;
            sql3="update college set c1='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            
            }
            if(p==1){
                v++;
              String sql3;
            sql3="update college set c2='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            
            }
            if(p==2){
                v++;
              String sql3;
            sql3="update college set c3='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
           
            }
            if(p==3){
                v++;
              String sql3;
            sql3="update college set c4='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            
            }
            if(p==4){
                v++;
              String sql3;
            sql3="update college set c5='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            
            }
            if(p==5){
                v++;
              String sql3;
            sql3="update college set c6='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
           
            }
            if(p==6){
                v++;
              String sql3;
            sql3="update college set c7='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            
            }
            if(p==7){
                v++;
              String sql3;
            sql3="update college set c8='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            
            }
            if(p==8){
                v++;
              String sql3;
            sql3="update college set c9='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            
            }
            if(p==9){
                v++;
              String sql3;
            sql3="update college set c10='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
          
            }
            jButton2.setVisible(false);
     jButton12.setVisible(false);
      jButton13.setVisible(false);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
       Loginpage h=new Loginpage();
       h.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton27ActionPerformed
static int i=1;
String d=Integer.toString(i);
PreparedStatement pst1=null;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane allot;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
