/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chintu
 */
import java.sql.*;
import javax.swing.*;

public class Loginpage extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;
    /**
     * Creates new form Loginpage
     */
    public Loginpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernamestudent = new javax.swing.JTextField();
        passwordstudent = new javax.swing.JPasswordField();
        loginstudent = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernamecollege = new javax.swing.JTextField();
        passwordcollege = new javax.swing.JPasswordField();
        logincollege = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        u = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        p = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("AR CENA", 1, 36)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Username:");

        jLabel4.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Password:");

        usernamestudent.setBackground(new java.awt.Color(0, 0, 51));
        usernamestudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usernamestudent.setForeground(new java.awt.Color(255, 255, 255));

        passwordstudent.setBackground(new java.awt.Color(0, 0, 51));
        passwordstudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordstudent.setForeground(new java.awt.Color(255, 255, 255));

        loginstudent.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        loginstudent.setText("Login");
        loginstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginstudentActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jButton2.setText("New User?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernamestudent, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(passwordstudent))
                .addContainerGap(409, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(260, 260, 260)
                .addComponent(loginstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(usernamestudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passwordstudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginstudent)
                    .addComponent(jButton2))
                .addContainerGap(280, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Student", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("User name:");

        jLabel2.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Password:");

        usernamecollege.setBackground(new java.awt.Color(0, 0, 51));
        usernamecollege.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usernamecollege.setForeground(new java.awt.Color(255, 255, 255));

        passwordcollege.setBackground(new java.awt.Color(0, 0, 51));
        passwordcollege.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordcollege.setForeground(new java.awt.Color(255, 255, 255));
        passwordcollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordcollegeActionPerformed(evt);
            }
        });

        logincollege.setBackground(new java.awt.Color(0, 0, 51));
        logincollege.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        logincollege.setText("Login");
        logincollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logincollegeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(407, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usernamecollege, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordcollege, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(logincollege)
                        .addGap(263, 263, 263))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamecollege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordcollege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addComponent(logincollege)
                .addContainerGap(283, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("College", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("User Name:");

        u.setBackground(new java.awt.Color(0, 0, 51));
        u.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        u.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Password:");

        p.setBackground(new java.awt.Color(0, 0, 51));
        p.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login and Allocate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(77, 77, 77)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(u)
                    .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addGap(269, 269, 269))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(jButton1)
                .addGap(170, 170, 170))
        );

        jTabbedPane1.addTab("Admin", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(675, 675, 675))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Student");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginstudentActionPerformed
        try{
           Class.forName("com.mysql.jdbc.Driver");
           conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
       
           String sql;
           sql="SELECT * FROM student "+"WHERE UserName=? and Password=?";
           pst=conn.prepareStatement(sql);
           pst.setString(1,usernamestudent.getText());
           pst.setString(2, passwordstudent.getText());
           rs=pst.executeQuery();
           if(rs.next()){
               JOptionPane.showMessageDialog(null,"login successful");
               home h=new home(rs);
               h.setVisible(true);
           }else{
               JOptionPane.showMessageDialog(null,"login unsuccessful");
           }
      }
      catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }                 
    }//GEN-LAST:event_loginstudentActionPerformed

    private void logincollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logincollegeActionPerformed
         try{
           Class.forName("com.mysql.jdbc.Driver");
           conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
       
           String sql;
           sql="SELECT * FROM college "+"WHERE Userid=? and Password=?";
           pst=conn.prepareStatement(sql);
           pst.setString(1,usernamecollege.getText());
           pst.setString(2, passwordcollege.getText());
           rs=pst.executeQuery();
           if(rs.next()){
               JOptionPane.showMessageDialog(null,"login successful");
               collegehome ch=new collegehome(rs);
               ch.setVisible(true);
           }else{
               JOptionPane.showMessageDialog(null,"login unsuccessful");
           }
      }
      catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      }                  
    }//GEN-LAST:event_logincollegeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String g=u.getText();
       String z=p.getText();
       if(g.equals("Ravi")&z.equals("1234")){
        int r=0;
      try{
      while(r<4){
          
            Class.forName("com.mysql.jdbc.Driver");
           conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
           int[] a=new int[120];
           int i=6;
           String sql1;
           sql1="SELECT * FROM student "+"WHERE Rank='"+r+"'";
           pst=conn.prepareStatement(sql1);
           ResultSet s1;
           s1=pst.executeQuery();
          if( s1.next()){
             int e=s1.getInt("status");
              if(e==1){
   while(i<126){
            
               int c=s1.getInt(i);
     if(c!=0){
               int d=c-1;
               
               int k=d/12;
               int p=d%12;
                String sql;
                 Class.forName("com.mysql.jdbc.Driver");
           conn=DriverManager.getConnection("jdbc:mysql://localhost/userdetails","root","1234");
           sql="SELECT * FROM college "+"WHERE id='"+k+"'";
           PreparedStatement pst2 =conn.prepareStatement(sql);
           ResultSet s;
           s=pst2.executeQuery();
           s.next();
           int v=s.getInt(p+7);
          
          
           if(v>0){
           String sql2;
            sql2="update student set final='"+c+"' where Rank='"+r+"'" ;
            pst=conn.prepareStatement(sql2);
            pst.executeUpdate();
           
            if(p==0){
                v--;
              String sql3;
            sql3="update college set c1='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            break;
            }
            if(p==1){
                v--;
              String sql3;
            sql3="update college set c2='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            break;
            }
            if(p==2){
                v--;
              String sql3;
            sql3="update college set c3='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
           break;
            }
            if(p==3){
                v--;
              String sql3;
            sql3="update college set c4='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            break;
            }
            if(p==4){
                v--;
              String sql3;
            sql3="update college set c5='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            break;
            }
            if(p==5){
                v--;
              String sql3;
            sql3="update college set c6='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            break;
            }
            if(p==6){
                v--;
              String sql3;
            sql3="update college set c7='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            break;
            }
            if(p==7){
                v--;
              String sql3;
            sql3="update college set c8='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            break;
            }
            if(p==8){
                v--;
              String sql3;
            sql3="update college set c9='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            break;
            }
            if(p==9){
                v--;
              String sql3;
            sql3="update college set c10='"+v+"' where id='"+k+"'" ;
            pst=conn.prepareStatement(sql3);
            pst.executeUpdate();
            break;
            }
           }
          
              i++; 
           
           }else{
               break;
          } 
           }
          }
          }
          r++;
          
      }
      }
      catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
      } 
       JOptionPane.showMessageDialog(null,"allocation finished");
       }else{
            JOptionPane.showMessageDialog(null,"login unsuccessful");
       }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passwordcollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordcollegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordcollegeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        register r=new register();
        r.setVisible(true);
        r.setLocationRelativeTo(null);
        r.pack();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logincollege;
    private javax.swing.JButton loginstudent;
    private javax.swing.JPasswordField p;
    private javax.swing.JPasswordField passwordcollege;
    private javax.swing.JPasswordField passwordstudent;
    private javax.swing.JTextField u;
    private javax.swing.JTextField usernamecollege;
    private javax.swing.JTextField usernamestudent;
    // End of variables declaration//GEN-END:variables
}
